### PR TITLE
Correctly handle negative normal forces when averaging in group

### LINKED ISSUE #8: [tactile_merger] Suggestion to publish also negative forces
Some customers are interested in having the _contact_states_ be published also when the _tactile_states_ messages contains negative values, potentially producing a negative averaged force for a "group" of taxel.
reasons invoked are : 
* seeing the vector of force displayed in rviz in all case positive and negative is a good way to find problems.
* negative forces can be measured by some tactile elements on sticky material, so should be displayed.

Currently it seems the design only accepts values higher than epsilon and positive https://github.com/ubi-agni/tactile_toolbox/blob/melodic-devel/tactile_merger/src/taxel_group.cpp#L111.

one open question is :
* should the feature of displaying negative forces be optional ? if yes, should it be default behaviour (non backward compatible) ?

### PR DESCRIPTION
**Pull request by rhaschke**
Fixes #8.

### CODE REVIEW

**Comment by guihomework** [comment]
I think this PR changes the direction of the display that we used to have, pushing forces are displayed pointing outwards the taxels
see comparison

before PR #11
Screenshot_2020-10-07_14-52-19_beforePR11_allpos1

PR #11 
Screenshot_2020-10-07_14-52-49_PR11_allpos1

**Comment by rhaschke** [comment]
Yes, sorry. I was testing with a wrong config...

**Comment by rhaschke** [comment]
Should be fixed now.

**Comment by GereonBuescher** [comment]
RP#11-test-inverted-force
I made a screenshot while pressing on palm and one fingertip, showing the inverted force direction. Here attached.
For testing the new palm sum I need to cheat with the joint stats, as the P6Leander currently have no bend-sensors.
-> As the palm thumb patches are associated / aligned to the thumb I should be able to obverse a change of vector sum when changing the thumb joint, right?

**Comment by guihomework** [comment]
Sign is good for me now. I think @GereonBuescher is testing too.

**Comment by rhaschke** [comment]
Rebased to resolve conflicts with #5 that was recently merged.

**Pull request merged**
